version: '3.8'

services:
  database:
    container_name: product_db
    image: postgres:13
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pa55w0rd
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

  product-ms:
    container_name: product_ms
    image: product-ms:1.0-SNAPSHOT
    ports:
      - "8001:8001"
    environment:
      DB_URL: jdbc:postgresql://database:5432/products
    depends_on:
      - database

volumes:
  products_data:

