server:
  port: 8001
spring:
  datasource:
    username: admin
    password: Pa55w0rd
    url: jdbc:postgresql://127.0.0.1:5432/products
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.hibernate: info